### ISSUE TITLE
Cannot disable docs endpoints

### ISSUE THREAD

**Issue by marcelogp** [cloudflare/itty-router-openapi#29]
Hello. I would like to control whether `/docs` and `/redocs` and `/openapi.json` endpoints are enabled or not. I see in the code the check below but it doesn't seem possible to pass `openapiConfig` as `undefined`.

https://github.com/cloudflare/itty-router-openapi/blob/main/src/openapi.ts#L103

**Comment by G4brym** [comment]
Hey @marcelogp i've just added support for disabling or changing the path for all theses routes in the latest release (v0.1.0)
You can see the new options in [here](https://github.com/cloudflare/itty-router-openapi#openapirouteroptions--)

**Comment by marceloverdijk** [comment]
@G4brym the [link ](https://github.com/cloudflare/itty-router-openapi#openapirouteroptions--) mentioned does not work unfortunately. How should I disable this?
