### ISSUE TITLE
Put an example of usage with modules syntax

### ISSUE THREAD

**Issue by gimenete** [cloudflare/itty-router-openapi#3]
Based on an example of the [itty router](https://itty-router.dev/#/#cf-es6-module-syntax) library I was doing:

```ts
const router = OpenAPIRouter();
// ...
const worker: ExportedHandler<Bindings> = { fetch: router.handle };
export default worker;
```

By doing this, even if the parameters were correct in a request, I was getting always an empty `data` argument.

I had to check the code of the library and realized that if you do that then the `data` argument for the `handle` methods is not the second argument, but the fourth, because the library passes as many arguments as the `router.handle` function receives, plus the `data`. It turns out that the `fetch` function receives not just the `Request` argument, but two additional ones: an `Env` and an `ExecutionContext`.

This works fine:

```ts
const router = OpenAPIRouter();
// ...

const worker: ExportedHandler<Bindings> = {
  fetch: (request /*, env, ctx */) => router.handle(request),
};

export default worker;
```

Thanks!

**Comment by G4brym** [comment]
Hey @gimenete
I've just merged a commit with a new section that cover this use case
Thanks for lettings us know 😃
