### ISSUE TITLE
Api docs generation is not working when nested routes.

### ISSUE THREAD

**Issue by truwater** [cloudflare/itty-router-openapi#30]
Routing works well with the following code.

<code>parentRouter.all('/child/*', childRouter.handle)</code>

But api docs generation is not working.

**Comment by G4brym** [comment]
Hey @truwater  i've just added support for nested routers in the latest release (v0.1.0)
You can see an example snippet [here](https://github.com/cloudflare/itty-router-openapi#7-nested-routers)
