### ISSUE TITLE
Nested router "No operations defined in spec"

### ISSUE THREAD

**Issue by jasiqli** [cloudflare/itty-router-openapi#51]
Same as #30 

Have tried setting up nested router *(as I often do in `itty-router`)* and while this works, I still see "No operations defined in spec!" when viewing `/docs`.

I've tested this on both my own projects and with the tasks example from Cloudflare Workers SDK which is at https://github.com/jasiqli/tasks-openapi-issue

---
Related to this, the example [7. Nested Routers](https://github.com/cloudflare/itty-router-openapi#7-nested-routers) shows
```
router.all('/api/v1/attacks/*', attacksRouter)
```
however I find this generates a *"c is not function"* error and the only way it will work *(as with `itty-router`)* is
```
router.all('/api/v1/attacks/*', attacksRouter.handle)
```

**Comment by G4brym** [comment]
Hey @jasiqli 
i've cloned your https://github.com/jasiqli/tasks-openapi-issue, and solved the issue by upgrading to the latest version of itty-router-openapi

**Comment by jasiqli** [comment]
Thanks @G4brym. Seems to work a treat 🎉
