### ISSUE TITLE
Support for minLength / maxLength strings

### ISSUE THREAD

**Issue by gimenete** [cloudflare/itty-router-openapi#55]
It'd be great to have support for `minLength` and `maxLength`.

Specially when you have a limit for a column in the database, it'd be nice to have the API to limit the value already and not have to do it manually inside the endpoint implementation.

This would also be useful for checking that a value is not an empty string by using `minLength: 1`, which is pretty common, I think.

**Comment by G4brym** [comment]
Hey @gimenete, i'm planning on deprecating the current types and replacing it with zod, then all these field parameters like what you are asking will became available
What do you think of this change to mainly use zod as definition and validation?

**Comment by gimenete** [comment]
@G4brym that'd be awesome. In fact I'm already using zod and from it I generate the open api types. See my comment here https://github.com/cloudflare/itty-router-openapi/issues/47#issuecomment-1531180686

So using zod directly would be much simpler!

**Comment by arjunyel** [comment]
@G4brym hi friend, is there any chance of instead of just using Zod make it pluggable? Personally I would like to use ArkType :) https://arktype.io/

**Comment by rhutikcodes** [comment]
any updates on this? Zod will be super useful :)

**Comment by G4brym** [comment]
Hey there, i've just published the new v1.0.0 release that adds Zod support everywhere
Learn more [here](https://cloudflare.github.io/itty-router-openapi/types/#zod-types)
