### ISSUE TITLE
Non-JSON request body causes error

### ISSUE THREAD

**Issue by rstml** [cloudflare/itty-router-openapi#64]
It seems that the router tries to parse and validate non-JSON request body and fails.

Example route:

```
export class ExampleRoute extends OpenAPIRoute {
    static schema = {
        // ...
        requestBody: {
            contentType: 'application/octet-stream'
        },
        // ...
    }
}
```

Error response:

```
{
  "errors": {
    "body": "Unexpected token 'R', \"Received: \"... is not valid JSON"
  },
  "success": false,
  "result": {}
}
```

The only way to avoid this is not to specify `requestBody` at all. In that case, however, `/docs` gets broken and doesn't allow to submit file as a request body.

**Comment by G4brym** [comment]
Hey @rstml i've published a new version (v0.1.10) that fixes this issue
