### ISSUE TITLE
raiseUnknownParameters raises error when query starts with sub delimiter

### ISSUE THREAD

**Issue by juliangehring** [cloudflare/itty-router-openapi#75]
The router currently returns a "400 Bad Request" error when:
- `raiseUnknownParameters` is set to true in the router configuration
- the query parameters start with a `&` (while it is unorthodox, this is allowed by RFC 3986)

Here an example based on the tutorial:
`http://server/api/list?&page=1&isCompleted=true`
which yields
> "errors":{"":"is an unknown parameter"}

I would have thought that no such error would be raised in this case, since there is no unknown parameter (i.e. none).

**Comment by G4brym** [comment]
Hey there, I've just published the new v1.0.0 release fixes this issue
Migration guide to 1.0.0 [available here](https://cloudflare.github.io/itty-router-openapi/migrating-to-1.0/)
